version: '3'

services:
  postgres:
    image: postgres
    environment:
      - 'POSTGRES_PASSWORD=postgres'
    networks:
      - postgreslocal
    ports:
      - '5432:5432'
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:

networks:
  postgreslocal:
    driver: bridge
